### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by zhenyanghua** [hobu/plasio-ui#8]
When I use the express mode and use the **Point Information** tool clicking on a point, upon the information retrieved, the following error is printed in the console:

> Failed to load http://c0.greyhound.io/resource/autzen/files/0: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:8001' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

What should I do to get rid of it?

**Comment by verma** [comment]
Interesting, what does your plasio-ui setup code look like?  Can you check if you have `allowGreyhoundCredentials` set to true?

**Comment by verma** [comment]
Since I haven't heard back, I will go ahead and close this issue, please feel free to re-open or create a new issue if things still don't work.
